### ISSUE TITLE
"this.taskFn is not a function" error on migrating with wp-xml

### ISSUE THREAD

**Issue by keerlu** [TryGhost/migrate#1153]
I'm getting an empty archive and some errors in the output when I run the following command:

```
migrate wp-xml --pathToFile drossbucket.wordpress.com-2024-08-05-18_54_57-tu0bwbn8bldaqwakjetpyvwvtibq3i2r.zip -V
```

I get the following output:

```bash
info Migrating from export at drossbucket.wordpress.com-2024-08-05-18_54_57-tu0bwbn8bldaqwakjetpyvwvtibq3i2r.zip
[2024-08-06 08:12:11] INFO
[STARTED] Initializing
[OUTPUT] Workspace initialized at /var/folders/td/rn_5xy2d6p72ft74ptc49z0w0000gn/T/mg/c103a6beee87ccaa1d3f0b2e8af57015-wordpress-drossbucket-wordpress-com-2024-08-05-18-54-57-tu0bwbn8bldaqwakjetpyvwvtibq3i2r
[COMPLETED] Initializing
[STARTED] Read xml file
(node:4422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [WriteStream]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:4422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [WriteStream]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:4422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
[COMPLETED] Read xml file
[STARTED] Fetch missing data via WebScraper
[FAILED] this.taskFn is not a function
[COMPLETED] Fetch missing data via WebScraper
[STARTED] Build Link Map
[COMPLETED] Build Link Map
[STARTED] Format data as Ghost JSON
[COMPLETED] Format data as Ghost JSON
[STARTED] Fetch images via AssetScraper
[STARTED] Initializing AssetScraper cache
[COMPLETED] Initializing AssetScraper cache
[STARTED] Finding files
[COMPLETED] Finding files
[STARTED] Finding file types
[COMPLETED] Finding file types
[STARTED] Downloading files
[COMPLETED] Downloading files
[STARTED] Fixing asset references
[COMPLETED] Fixing asset references
[STARTED] Finalizing
[COMPLETED] Finalizing
[COMPLETED] Fetch images via AssetScraper
[STARTED] Update links in content via LinkFixer
[SKIPPED] Link map not available
[STARTED] Convert HTML -> MobileDoc
[COMPLETED] Convert HTML -> MobileDoc
[STARTED] Write Ghost import JSON File
[COMPLETED] Write Ghost import JSON File
[STARTED] Write Ghost import zip
[OUTPUT] Successfully written zip to /Users/lucykeer/Downloads/gh-wordpress-drossbucket-wordpress-com-2024-08-05-18-54-57-tu0bwbn8bldaqwakjetpyvwvtibq3i2r-1722928331467.zip in 66ms
[COMPLETED] Write Ghost import zip
[2024-08-06 08:12:11] INFO
info Done {
  posts: [],
  users: [],
  tags: [],
  posts_authors: [],
  posts_tags: [],
  posts_meta: []
}
Error: ENOENT: no such file or directory, open '/Users/lucykeer/Downloads/localhost_development.log'
    at readFileSync (node:fs:448:20)
    at showLogs (file:///Users/lucykeer/.nvm/versions/node/v20.16.0/lib/node_modules/@tryghost/migrate/lib/utilties/cli-log-display.js:8:21)
    at TypeCommand.run [as _runHandler] (file:///Users/lucykeer/.nvm/versions/node/v20.16.0/lib/node_modules/@tryghost/migrate/commands/wp-xml.js:197:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 27)
```

**Comment by PaulAdamDavis** [comment]
A year later 😅 but this is likely not an issue anymore. The logging error at the end of this output won't happen anymore as the logs were ripped out.

If this issue crops up again, please do let me know!
