### ISSUE TITLE
Most of dependency are deprecated, please fix it.

### ISSUE THREAD

**Issue by rafidalhaque** [TryGhost/migrate#525]
Hello, when I going install this tool, it shows me this output.
```
$ npm install --global @tryghost/migrate
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated hubspot-api@2.15.3: No longer maintained, please use @hubspot/api-client instead
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated superagent@4.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
/home/rafidalhaque/.nvm/versions/node/v14.19.3/bin/migrate -> /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/bin/cli.js
+ @tryghost/migrate@0.22.7
updated 1 package in 239.056s
```

### When I run this tool, it shows me this error message.
```
$ migrate wp-api https://redwanrawaha.wordpress.com
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@tryghost/mg-mediascraper'
Require stack:
- /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/sources/ghost.js
- /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/commands/ghost.js
- /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/node_modules/sywac/api.js
- /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/node_modules/@tryghost/pretty-cli/lib/pretty-cli.js
- /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/node_modules/@tryghost/pretty-cli/index.js
- /home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/sources/ghost.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/commands/ghost.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/sources/ghost.js',
    '/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/commands/ghost.js',
    '/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/node_modules/sywac/api.js',
    '/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/node_modules/@tryghost/pretty-cli/lib/pretty-cli.js',
    '/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/node_modules/@tryghost/pretty-cli/index.js',
    '/home/rafidalhaque/.nvm/versions/node/v14.19.3/lib/node_modules/@tryghost/migrate/bin/cli.js'
  ]
}
```

**Comment by phrasenmaeher** [comment]
I am also having this problem.

**Comment by rafidalhaque** [comment]
> I am also having this problem.

Then I use the official ghost plugin in wordpress for migrating to ghost from wordpress.

**Comment by PaulAdamDavis** [comment]
These tools recently had a huge upgrade, bringing everything up to date. They are now ESM only.
