### ISSUE TITLE
json-html command error

### ISSUE THREAD

**Issue by securibee** [TryGhost/migrate#628]
Running into the following error while running `migrate json-html /test/ghost.json -V` to migrate HTML to Ghost mobiledoc format.

Error:
```
info Running html conversion on /test/ghost.json
info Done with errors []
TypeError: Cannot read properties of undefined (reading 'cacheDir')
    at TypeCommand.run [as _runHandler] (file:///usr/local/lib/node_modules/@tryghost/migrate/commands/json/html.js:47:71)
    at /usr/local/lib/node_modules/@tryghost/migrate/node_modules/sywac/types/command.js:131:19
    at async Promise.all (index 10)
```

/test/ghost.json:
```
{
  "posts": [
    {
      "html": "<p>this is a test</p>"
    }
  ]
}
```

I could be missing something.

**Comment by PaulAdamDavis** [comment]
Hi @securibee, thanks for reporting this! I was able to reproduce this, so I've fixed the issue and published version 0.29.5 to NPM.
